package com.example.banquemisrchallenge05movieapp.utils.test_utils.forlocal

import com.example.banquemisrchallenge05movieapp.utils.shared_models.Genre
import com.example.banquemisrchallenge05movieapp.utils.shared_models.MovieDbResultUpcoming
import com.example.banquemisrchallenge05movieapp.utils.shared_models.MovieDetails
import com.example.banquemisrchallenge05movieapp.utils.shared_models.ProductionCompany
import com.example.banquemisrchallenge05movieapp.utils.shared_models.ProductionCountry
import com.example.banquemisrchallenge05movieapp.utils.shared_models.SpokenLanguage

val fakeLocalMoviesDetails: MutableList<MovieDetails> = mutableListOf()
